### ISSUE TITLE
Error with 7Z containing jdk

### ISSUE THREAD

**Issue by electricJP** [mkht/7ZipArchiveDsc#4]
I'm trying to use 7ZipArchiveDsc to expand a 7Z file containing a jdk folder but somehow I get this error:

VERBOSE: [MDC-MON01]:                            [[x7ZipArchive]LogStash] Extracting archive: c:\windows\temp\dsc\logstash.7z to c:\logstash
Access to the path 'C:\logstash\a6e34166-0b36-4f99-b75b-337a3a343e12\logstash\jdk1.8.0_192' is denied.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.IO.IOException,Set-TargetResource
    + PSComputerName        : mdc-mon01.gameloft.org

Expanding this archive manually (ie 7z.exe x logstash.7z) works normally.

**Comment by electricJP** [comment]
in case needed, here is the DSC:

x7ZipArchive LogStash
        {
            Path = "c:\windows\temp\dsc\logstash.7z"
            Destination = "c:\logstash"
            IgnoreRoot = $true
            Clean = $true
            dependsOn = "[script]Stop-logstash"
        }

**Comment by mkht** [comment]
@electricJP 
I'm sorry for late reply.
I tried to reproduce the issue, but I can't. 😕 

Perhaps this line is causing an exception, but the cause has not been determined.
https://github.com/mkht/7ZipArchiveDsc/blob/a4828fdb65e2bd1f8ff78177b6eeacc7d9503358/DSCResources/x7ZipArchive/x7ZipArchive.psm1#L275-L282

Could you upload a 7z file that can reproduce the issue?

**Comment by electricJP** [comment]
I used 7zip directly as a workaround; the same file was okay with it. I did not tried with other 7z files as I solved my problem another way. sorry.
