### ISSUE TITLE
use pipeline

### ISSUE THREAD

**Issue by msjzs** [mkht/7ZipArchiveDsc#5]
can I expand zip like this
Get-Item -Path .\t.7z | Expand-7ZipArchive -Destination .\ok

**Comment by mkht** [comment]
Hi @msjzs 
Sorry. The current implementation cannot accept pipeline input.
You can use `ForEach-Object` to write in a way that is similar to a pipeline.

```PowerShell
Get-Item .\t.7z | ForEach-Object { Expand-7ZipArchive -Path $_.FullName -Destination .\ok }
```

It would certainly be better to accept pipeline input. I will work on improving it if I have time over the weekend. 😄

**Comment by msjzs** [comment]
thank you
