### ISSUE TITLE
Problem with Int32 value in Test-TargetResource

### ISSUE THREAD

**Issue by TMattes** [mkht/7ZipArchiveDsc#7]
We are facing a problem when a large zip-archive (> 2GB) is extracted on the target machine. The error message indicates an overflow. This is the error message:
PowerShell DSC resource x7ZipArchive  failed to execute Test-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot convert value "2179746370" to type "System.Int32". Error: "Value was either too large or too small for an Int32."

**Comment by mkht** [comment]
Thank you for your report. We will investigate this issue and report back to you as soon as we have more information.

**Comment by TMattes** [comment]
Thank you for your reply. What information do you need from me? Target system specifications or something like that?

**Comment by mkht** [comment]
If possible, I would be glad if you could provide a ZIP archive that could reproduce the problem.

**Comment by TMattes** [comment]
Oh, this is a little bit difficult, because the zip file which causes the problem contains files we are not allowed to share. Furthermore, a file sized more than 2 GB is not really suitable for an upload to the internet, is it? ;)
But, in fact, this only happens with this one zip file >2 GB. Some others, partly sized >1GB do not show this error. Furthermore, all zips we expand contain a lot of small files. Maybe, this information helps.

**Comment by mkht** [comment]
I understand that is difficult. Perhaps I can create a ZIP archive that can reproduce the problem myself. Don't worry about it. 😉

**Comment by mkht** [comment]
We have released **v1.8.2** which may fixes the issue, please try it.

This error was occurring when the archive contained files larger than 2GB.
(Note that it is not the file size of the archive itself)

The file size larger than 2147483647 bytes (=2GB) was not parsed because the incorrect `int32` type was selected for the property holding the file size. This has been corrected to `long` type and this issue has been solved.

**Comment by TMattes** [comment]
Thank you so much! This fixed the problem! :)
